/// EsBluetooth.MFGdefs.h
/// Bluetooth manufacturers definitions MACRO-X file
/// !DO NOT INCLUDE THIS FILE IN PROJECT!
/// It's included implicitly in EsBluetooth.h and EsBluetooth.cpp
/// as appropriate.
/// MFG_MAP_ENTRY(sym, val, str)
///
MFG_MAP_BEGIN
MFG_MAP_ENTRY( MFG_ERICSSON,                                    0,    esT("Ericsson") )
MFG_MAP_ENTRY( MFG_NOKIA,                                       1,    esT("Nokia") )
MFG_MAP_ENTRY( MFG_INTEL,                                       2,    esT("Intel") )
MFG_MAP_ENTRY( MFG_IBM,                                         3,    esT("IBM") )
MFG_MAP_ENTRY( MFG_TOSHIBA,                                     4,    esT("Toshiba") )
MFG_MAP_ENTRY( MFG_3COM,                                        5,    esT("3-Com") )
MFG_MAP_ENTRY( MFG_MICROSOFT,                                   6,    esT("Microsoft") )
MFG_MAP_ENTRY( MFG_LUCENT,                                      7,    esT("Lucent") )
MFG_MAP_ENTRY( MFG_MOTOROLA,                                    8,    esT("Motorola") )
MFG_MAP_ENTRY( MFG_INFINEON,                                    9,    esT("Infineon") )
MFG_MAP_ENTRY( MFG_CSR,                                         10,   esT("CSR") )
MFG_MAP_ENTRY( MFG_SILICONWAVE,                                 11,   esT("Silicon Wave") )
MFG_MAP_ENTRY( MFG_DIGIANSWER,                                  12,   esT("Digianswer") )
MFG_MAP_ENTRY( MFG_TI,                                          13,   esT("Texas Instruments") )
MFG_MAP_ENTRY( MFG_PARTHUS,                                     14,   esT("Parthus") )
MFG_MAP_ENTRY( MFG_BROADCOM,                                    15,   esT("Broadcom") )
MFG_MAP_ENTRY( MFG_MITEL,                                       16,   esT("Mitel") )
MFG_MAP_ENTRY( MFG_WIDCOMM,                                     17,   esT("WIDCOMM") )
MFG_MAP_ENTRY( MFG_ZEEVO,                                       18,   esT("Zeevo") )
MFG_MAP_ENTRY( MFG_ATMEL,                                       19,   esT("Atmel") )
MFG_MAP_ENTRY( MFG_MITSIBUSHI,                                  20,   esT("Mitsubishi") )
MFG_MAP_ENTRY( MFG_RTX_TELECOM,                                 21,   esT("RTX Telecom") )
MFG_MAP_ENTRY( MFG_KC_TECHNOLOGY,                               22,   esT("KC Technology") )
MFG_MAP_ENTRY( MFG_NEWLOGIC,                                    23,   esT("NewLogic") )
MFG_MAP_ENTRY( MFG_TRANSILICA,                                  24,   esT("Transilica") )
MFG_MAP_ENTRY( MFG_ROHDE_SCHWARZ,                               25,   esT("Rohde-Schwartz") )
MFG_MAP_ENTRY( MFG_TTPCOM,                                      26,   esT("TTPCOM") )
MFG_MAP_ENTRY( MFG_SIGNIA,                                      27,   esT("SIGNIA") )
MFG_MAP_ENTRY( MFG_CONEXANT,                                    28,   esT("Conexant") )
MFG_MAP_ENTRY( MFG_QUALCOMM,                                    29,   esT("Qualcomm") )
MFG_MAP_ENTRY( MFG_INVENTEL,                                    30,   esT("Inventel") )
MFG_MAP_ENTRY( MFG_AVM_BERLIN,                                  31,   esT("AVM Berlin") )
MFG_MAP_ENTRY( MFG_BANDSPEED,                                   32,   esT("Bandspeed") )
MFG_MAP_ENTRY( MFG_MANSELLA,                                    33,   esT("Mansella") )
MFG_MAP_ENTRY( MFG_NEC,                                         34,   esT("NEC") )
MFG_MAP_ENTRY( MFG_WAVEPLUS_TECH_CO,                            35,   esT("WavePlus Technology") )
MFG_MAP_ENTRY( MFG_ALCATEL,                                     36,   esT("Alcatel") )
MFG_MAP_ENTRY( MFG_PHILIPS_SEMICONDUCTOR,                       37,   esT("NXP (formerly Philips) Semiconductor") )
MFG_MAP_ENTRY( MFG_C_TECHNOLOGIES,                              38,   esT("C Technologies") )
MFG_MAP_ENTRY( MFG_OPEN_INTERFACE,                              39,   esT("Open Interface") )
MFG_MAP_ENTRY( MFG_RF_MICRO_DEVICES,                            40,   esT("RF Micro Devices") )
MFG_MAP_ENTRY( MFG_HITACHI,                                     41,   esT("Hitachi") )
MFG_MAP_ENTRY( MFG_SYMBOL_TECHNOLOGIES,                         42,   esT("Symbol Technologies") )
MFG_MAP_ENTRY( MFG_TENOVIS,                                     43,   esT("Tenovis") )
MFG_MAP_ENTRY( MFG_MACRONIX_INTERNATIONAL,                      44,   esT("Macronix International") )
MFG_MAP_ENTRY( MFG_GCT_SEMICONDUCTOR,                           45,   esT("GCT Semiconductor") )
MFG_MAP_ENTRY( MFG_NORWOOD_SYSTEMS,                             46,   esT("Norwood Systems") )
MFG_MAP_ENTRY( MFG_MEWTEL_TECH_INC,                             47,   esT("MewTel Technology Inc.") )
MFG_MAP_ENTRY( MFG_ST_MICROELECTRONICS,                         48,   esT("ST Microelectronics") )
MFG_MAP_ENTRY( MFG_SYNOPSIS,                                    49,   esT("Synopsis") )
MFG_MAP_ENTRY( MFG_RED_MLTD,                                    50,   esT("Red-M (Communications) Ltd") )
MFG_MAP_ENTRY( MFG_COMMIL_LTD,                                  51,   esT("Commil Ltd") )
MFG_MAP_ENTRY( MFG_COMPUTER_ACCESS_TECH_CORP,                   52,   esT("Computer Access Technology Corporation (CATC)") )
MFG_MAP_ENTRY( MFG_ECLIPSESL,                                   53,   esT("Eclipse (HQ Espana) S.L.") )
MFG_MAP_ENTRY( MFG_RENESAS_TECH_CORP,                           54,   esT("Renesas Technology Corp.") )
MFG_MAP_ENTRY( MFG_MOBILIAN_CORP,                               55,   esT("Mobilian Corporation") )
MFG_MAP_ENTRY( MFG_TERAX,                                       56,   esT("Terax") )
MFG_MAP_ENTRY( MFG_INTEGRATED_SYSTEM_SOLUTION_CORP,             57,   esT("Integrated System Solution Corp.") )
MFG_MAP_ENTRY( MFG_MATSUSHITA_ELECTRIC_INDUSTRIAL_CO,           58,   esT("Matsushita Electric Industrial Co., Ltd.") )
MFG_MAP_ENTRY( MFG_GENNUM_CORP,                                 59,   esT("Gennum Corporation") )
MFG_MAP_ENTRY( MFG_RESEARCH_IN_MOTION,                          60,   esT("Research In Motion") )
MFG_MAP_ENTRY( MFG_IPEXTREME,                                   61,   esT("IPextreme, Inc.") )
MFG_MAP_ENTRY( MFG_SYSTEMS_AND_CHIPS,                           62,   esT("Systems and Chips, Inc.") )
MFG_MAP_ENTRY( MFG_BLUETOOTH_SIG,                               63,   esT("Bluetooth SIG, Inc.") )
MFG_MAP_ENTRY( MFG_SEIKO_EPSON_CORP,                            64,   esT("Seiko Epson Corporation") )
MFG_MAP_ENTRY( MFG_INTEGRATED_SILICON_SOLUTION_TAIWAN,          65,   esT("Integrated Silicon Solution Taiwan, Inc.") )
MFG_MAP_ENTRY( MFG_CONWISE_TECH_CORP_LTD,                       66,   esT("CONWISE Technology Corporation Ltd") )
MFG_MAP_ENTRY( MFG_PARROT_SA,                                   67,   esT("PARROT SA") )
MFG_MAP_ENTRY( MFG_SOCKET_MOBILE,                               68,   esT("Socket Mobile") )
MFG_MAP_ENTRY( MFG_ATHEROS_COMMUNICATIONS,                      69,   esT("Atheros Communications, Inc.") )
MFG_MAP_ENTRY( MFG_MEDIATEK,                                    70,   esT("MediaTek, Inc.") )
MFG_MAP_ENTRY( MFG_BLUEGIGA,                                    71,   esT("Bluegiga") )
MFG_MAP_ENTRY( MFG_MARVELL_TECH_GROUP_LTD,                      72,   esT("Marvell Technology Group Ltd.") )
MFG_MAP_ENTRY( MFG_3DSP_CORP,                                   73,   esT("3DSP Corporation") )
MFG_MAP_ENTRY( MFG_ACCEL_SEMICONDUCTOR_LTD,                     74,   esT("Accel Semiconductor Ltd.") )
MFG_MAP_ENTRY( MFG_CONTINENTAL_AUTOMOTIVE_SYSTEMS,              75,   esT("Continental Automotive Systems") )
MFG_MAP_ENTRY( MFG_APPLE,                                       76,   esT("Apple, Inc.") )
MFG_MAP_ENTRY( MFG_STACCATO_COMMUNICATIONS,                     77,   esT("Staccato Communications, Inc.") )
MFG_MAP_ENTRY( MFG_AVAGO_TECHNOLOGIES,                          78,   esT("Avago Technologies") )
MFG_MAP_ENTRY( MFG_APT_LICENSING_LTD,                           79,   esT("APT Licensing Ltd.") )
MFG_MAP_ENTRY( MFG_SIRF_TECH,                                   80,   esT("SiRF Technology") )
MFG_MAP_ENTRY( MFG_TZERO_TECHNOLOGIES,                          81,   esT("Tzero Technologies, Inc.") )
MFG_MAP_ENTRY( MFG_JM_CORP,                                     82,   esT("J&M Corporation") )
MFG_MAP_ENTRY( MFG_FREE2MOVE_AB,                                83,   esT("Free2move AB") )
MFG_MAP_ENTRY( MFG_3DIJOY_CORP,                                 84,   esT("3DiJoy Corporation") )
MFG_MAP_ENTRY( MFG_PLANTRONICS,                                 85,   esT("Plantronics, Inc.") )
MFG_MAP_ENTRY( MFG_SONY_ERICSSON_MOBILE_COMMUNICATIONS,         86,   esT("Sony Ericsson Mobile Communications") )
MFG_MAP_ENTRY( MFG_HARMAN_INTERNATIONAL_INDUSTRIES,             87,   esT("Harman International Industries, Inc.") )
MFG_MAP_ENTRY( MFG_VIZIO,                                       88,   esT("Vizio, Inc.") )
MFG_MAP_ENTRY( MFG_NORDIC_SEMICONDUCTOR_ASA,                    89,   esT("Nordic Semiconductor ASA") )
MFG_MAP_ENTRY( MFG_EM_MICROELECTRONIC_MARIN_SA,                 90,   esT("EM Microelectronic-Marin SA") )
MFG_MAP_ENTRY( MFG_RALINK_TECH_CORP,                            91,   esT("Ralink Technology Corporation") )
MFG_MAP_ENTRY( MFG_BELKIN_INTERNATIONAL,                        92,   esT("Belkin International, Inc.") )
MFG_MAP_ENTRY( MFG_REALTEK_SEMICONDUCTOR_CORP,                  93,   esT("Realtek Semiconductor Corporation") )
MFG_MAP_ENTRY( MFG_STONESTREET_ONE,                             94,   esT("Stonestreet One, LLC") )
MFG_MAP_ENTRY( MFG_WICENTRIC,                                   95,   esT("Wicentric, Inc.") )
MFG_MAP_ENTRY( MFG_RIVIERAWAVES_SAS,                            96,   esT("RivieraWaves S.A.S") )
MFG_MAP_ENTRY( MFG_RDA_MICROELECTRONICS,                        97,   esT("RDA Microelectronics") )
MFG_MAP_ENTRY( MFG_GIBSON_GUITARS,                              98,   esT("Gibson Guitars") )
MFG_MAP_ENTRY( MFG_MICOMMAND_INC,                               99,   esT("MiCommand Inc.") )
MFG_MAP_ENTRY( MFG_BAND_XI_INTERNATIONAL,                       100,  esT("Band XI International, LLC") )
MFG_MAP_ENTRY( MFG_HEWLETT_PACKARD_COMPANY,                     101,  esT("Hewlett-Packard Company") )
MFG_MAP_ENTRY( MFG_9SOLUTIONS_OY,                               102,  esT("9Solutions Oy") )
MFG_MAP_ENTRY( MFG_GN_NETCOM_AS,                                103,  esT("GN Netcom A/S") )
MFG_MAP_ENTRY( MFG_GENERAL_MOTORS,                              104,  esT("General Motors") )
MFG_MAP_ENTRY( MFG_AD_ENGINEERING,                              105,  esT("A&D Engineering, Inc.") )
MFG_MAP_ENTRY( MFG_MINDTREE_LTD,                                106,  esT("MindTree Ltd.") )
MFG_MAP_ENTRY( MFG_POLAR_ELECTRO_OY,                            107,  esT("Polar Electro OY") )
MFG_MAP_ENTRY( MFG_BEAUTIFUL_ENTERPRISE_CO,                     108,  esT("Beautiful Enterprise Co., Ltd.") )
MFG_MAP_ENTRY( MFG_BRIARTEK,                                    109,  esT("BriarTek, Inc.") )
MFG_MAP_ENTRY( MFG_SUMMIT_DATA_COMMUNICATIONS,                  110,  esT("Summit Data Communications, Inc.") )
MFG_MAP_ENTRY( MFG_SOUND_ID,                                    111,  esT("Sound ID") )
MFG_MAP_ENTRY( MFG_MONSTER,                                     112,  esT("Monster, LLC") )
MFG_MAP_ENTRY( MFG_CONNECTBLUE_AB,                              113,  esT("connectBlue AB") )
MFG_MAP_ENTRY( MFG_SHANGHAI_SUPER_SMART_ELECTRONICS_CO_LTD,     114,  esT("ShangHai Super Smart Electronics Co. Ltd.") )
MFG_MAP_ENTRY( MFG_GROUP_SENSE_LTD,                             115,  esT("Group Sense Ltd.") )
MFG_MAP_ENTRY( MFG_ZOMM,                                        116,  esT("Zomm, LLC") )
MFG_MAP_ENTRY( MFG_SAMSUNG_ELECTRONICS_CO_LTD,                  117,  esT("Samsung Electronics Co. Ltd.") )
MFG_MAP_ENTRY( MFG_CREATIVE_TECH_LTD,                           118,  esT("Creative Technology Ltd.") )
MFG_MAP_ENTRY( MFG_LAIRD_TECHNOLOGIES,                          119,  esT("Laird Technologies") )
MFG_MAP_ENTRY( MFG_NIKE,                                        120,  esT("Nike, Inc.") )
MFG_MAP_ENTRY( MFG_LESSWIRE_AG,                                 121,  esT("lesswire AG") )
MFG_MAP_ENTRY( MFG_MSTAR_SEMICONDUCTOR,                         122,  esT("MStar Semiconductor, Inc.") )
MFG_MAP_ENTRY( MFG_HANLYNN_TECHNOLOGIES,                        123,  esT("Hanlynn Technologies") )
MFG_MAP_ENTRY( MFG_AR_CAMBRIDGE,                                124,  esT("A & R Cambridge") )
MFG_MAP_ENTRY( MFG_SEERS_TECH_CO_LTD,                           125,  esT("Seers Technology Co. Ltd") )
MFG_MAP_ENTRY( MFG_SPORTS_TRACKING_TECHNOLOGIES_LTD,            126,  esT("Sports Tracking Technologies Ltd.") )
MFG_MAP_ENTRY( MFG_AUTONET_MOBILE,                              127,  esT("Autonet Mobile") )
MFG_MAP_ENTRY( MFG_DELORME_PUBLISHING_COMPANY,                  128,  esT("DeLorme Publishing Company, Inc.") )
MFG_MAP_ENTRY( MFG_WUXI_VIMICRO,                                129,  esT("WuXi Vimicro") )
MFG_MAP_ENTRY( MFG_SENNHEISER_COMMUNICATIONS_AS,                130,  esT("Sennheiser Communications A/S") )
MFG_MAP_ENTRY( MFG_TIMEKEEPING_SYSTEMS,                         131,  esT("TimeKeeping Systems, Inc.") )
MFG_MAP_ENTRY( MFG_LUDUS_HELSINKI_LTD,                          132,  esT("Ludus Helsinki Ltd.") )
MFG_MAP_ENTRY( MFG_BLUERADIOS,                                  133,  esT("BlueRadios, Inc.") )
MFG_MAP_ENTRY( MFG_EQUINOX_AG,                                  134,  esT("equinox AG") )
MFG_MAP_ENTRY( MFG_GARMIN_INTERNATIONAL,                        135,  esT("Garmin International, Inc.") )
MFG_MAP_ENTRY( MFG_ECOTEST,                                     136,  esT("Ecotest") )
MFG_MAP_ENTRY( MFG_GN_RESOUND_AS,                               137,  esT("GN ReSound A/S") )
MFG_MAP_ENTRY( MFG_JAWBONE,                                     138,  esT("Jawbone") )
MFG_MAP_ENTRY( MFG_TOPCORN_POSITIONING_SYSTEMS,                 139,  esT("Topcorn Positioning Systems, LLC") )
MFG_MAP_ENTRY( MFG_GIMBAL_INC,                                  140,  esT("Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)") )
MFG_MAP_ENTRY( MFG_ZSCAN_SOFTWARE,                              141,  esT("Zscan Software") )
MFG_MAP_ENTRY( MFG_QUINTIC_CORP,                                142,  esT("Quintic Corp.") )
MFG_MAP_ENTRY( MFG_STOLLMAN_EV_GMBH,                            143,  esT("Stollman E+V GmbH") )
MFG_MAP_ENTRY( MFG_FUNAI_ELECTRIC_CO,                           144,  esT("Funai Electric Co., Ltd.") )
MFG_MAP_ENTRY( MFG_ADVANCED_PANMOBIL_SYSTEMS_GMBHCO_KG,         145,  esT("Advanced PANMOBIL Systems GmbH & Co. KG") )
MFG_MAP_ENTRY( MFG_THINKOPTICS,                                 146,  esT("ThinkOptics, Inc.") )
MFG_MAP_ENTRY( MFG_UNIVERSAL_ELECTRONICS,                       147,  esT("Universal Electronics, Inc.") )
MFG_MAP_ENTRY( MFG_AIROHA_TECH_CORP,                            148,  esT("Airoha Technology Corp.") )
MFG_MAP_ENTRY( MFG_NEC_LIGHTING,                                149,  esT("NEC Lighting, Ltd.") )
MFG_MAP_ENTRY( MFG_ODM_TECH,                                    150,  esT("ODM Technology, Inc.") )
MFG_MAP_ENTRY( MFG_CONNECTEDEVICE_LTD,                          151,  esT("ConnecteDevice Ltd.") )
MFG_MAP_ENTRY( MFG_ZER01TV_GMBH,                                152,  esT("Zer01.tv GmbH") )
MFG_MAP_ENTRY( MFG_ITECH_DYNAMIC_GLOBAL_DISTRIBUTION_LTD,       153,  esT("i.Tech Dynamic Global Distribution Ltd.") )
MFG_MAP_ENTRY( MFG_ALPWISE,                                     154,  esT("Alpwise") )
MFG_MAP_ENTRY( MFG_JIANGSU_TOPPOWER_AUTOMOTIVE_ELECTRONICS_CO,  155,  esT("Jiangsu Toppower Automotive Electronics Co., Ltd.") )
MFG_MAP_ENTRY( MFG_COLORFY,                                     156,  esT("Colorfy, Inc.") )
MFG_MAP_ENTRY( MFG_GEOFORCE_INC,                                157,  esT("Geoforce Inc.") )
MFG_MAP_ENTRY( MFG_BOSE_CORP,                                   158,  esT("Bose Corporation") )
MFG_MAP_ENTRY( MFG_SUUNTO_OY,                                   159,  esT("Suunto Oy") )
MFG_MAP_ENTRY( MFG_KENSINGTON_COMPUTER_PRODUCTS_GROUP,          160,  esT("Kensington Computer Products Group") )
MFG_MAP_ENTRY( MFG_SR_MEDIZINELEKTRONIK,                        161,  esT("SR-Medizinelektronik") )
MFG_MAP_ENTRY( MFG_VERTU_CORP_LIMITED,                          162,  esT("Vertu Corporation Limited") )
MFG_MAP_ENTRY( MFG_META_WATCH_LTD,                              163,  esT("Meta Watch Ltd.") )
MFG_MAP_ENTRY( MFG_LINAK_AS,                                    164,  esT("LINAK A/S") )
MFG_MAP_ENTRY( MFG_OTL_DYNAMICS_LLC,                            165,  esT("OTL Dynamics LLC") )
MFG_MAP_ENTRY( MFG_PANDA_OCEAN_INC,                             166,  esT("Panda Ocean Inc.") )
MFG_MAP_ENTRY( MFG_VISTEON_CORP,                                167,  esT("Visteon Corporation") )
MFG_MAP_ENTRY( MFG_ARP_DEVICES_LIMITED,                         168,  esT("ARP Devices Limited") )
MFG_MAP_ENTRY( MFG_MAGNETI_MARELLI_SPA,                         169,  esT("Magneti Marelli S.p.A") )
MFG_MAP_ENTRY( MFG_CAEN_RFID_SRL,                               170,  esT("CAEN RFID srl") )
MFG_MAP_ENTRY( MFG_INGENIEUR_SYSTEMGRUPPE_ZAHN_GMBH,            171,  esT("Ingenieur-Systemgruppe Zahn GmbH") )
MFG_MAP_ENTRY( MFG_GREEN_THROTTLE_GAMES,                        172,  esT("Green Throttle Games") )
MFG_MAP_ENTRY( MFG_PETER_SYSTEMTECHNIK_GMBH,                    173,  esT("Peter Systemtechnik GmbH") )
MFG_MAP_ENTRY( MFG_OMEGAWAVE_OY,                                174,  esT("Omegawave Oy") )
MFG_MAP_ENTRY( MFG_CINETIX,                                     175,  esT("Cinetix") )
MFG_MAP_ENTRY( MFG_PASSIF_SEMICONDUCTOR_CORP,                   176,  esT("Passif Semiconductor Corp") )
MFG_MAP_ENTRY( MFG_SARIS_CYCLING_GROUP,                         177,  esT("Saris Cycling Group, Inc") )
MFG_MAP_ENTRY( MFG_BEKEY_AS,                                    178,  esT("Bekey A/S") )
MFG_MAP_ENTRY( MFG_CLARINOX_TECHNOLOGIES_PTY_LTD,               179,  esT("Clarinox Technologies Pty. Ltd.") )
MFG_MAP_ENTRY( MFG_BDE_TECH_CO,                                 180,  esT("BDE Technology Co., Ltd.") )
MFG_MAP_ENTRY( MFG_SWIRL_NETWORKS,                              181,  esT("Swirl Networks") )
MFG_MAP_ENTRY( MFG_MESO_INTERNATIONAL,                          182,  esT("Meso international") )
MFG_MAP_ENTRY( MFG_TRELAB_LTD,                                  183,  esT("TreLab Ltd") )
MFG_MAP_ENTRY( MFG_QUALCOMM_INNOVATION_CENTER,                  184,  esT("Qualcomm Innovation Center, Inc. (QuIC)") )
MFG_MAP_ENTRY( MFG_JOHNSON_CONTROLS,                            185,  esT("Johnson Controls, Inc.") )
MFG_MAP_ENTRY( MFG_STARKEY_LABORATORIES_INC,                    186,  esT("Starkey Laboratories Inc.") )
MFG_MAP_ENTRY( MFG_S_POWER_ELECTRONICS_LIMITED,                 187,  esT("S-Power Electronics Limited") )
MFG_MAP_ENTRY( MFG_ACE_SENSOR_INC,                              188,  esT("Ace Sensor Inc") )
MFG_MAP_ENTRY( MFG_APLIX_CORP,                                  189,  esT("Aplix Corporation") )
MFG_MAP_ENTRY( MFG_AAMP_OF_AMERICA,                             190,  esT("AAMP of America") )
MFG_MAP_ENTRY( MFG_STALMART_TECH_LIMITED,                       191,  esT("Stalmart Technology Limited") )
MFG_MAP_ENTRY( MFG_AMICCOM_ELECTRONICS_CORP,                    192,  esT("AMICCOM Electronics Corporation") )
MFG_MAP_ENTRY( MFG_SHENZHEN_EXCELSECU_DATA_TECH_CO,             193,  esT("Shenzhen Excelsecu Data Technology Co.,Ltd") )
MFG_MAP_ENTRY( MFG_GENEQ_INC,                                   194,  esT("Geneq Inc.") )
MFG_MAP_ENTRY( MFG_ADIDAS_AG,                                   195,  esT("Adidas AG") )
MFG_MAP_ENTRY( MFG_LG_ELECTRONICS,                              196,  esT("LG Electronics") )
MFG_MAP_ENTRY( MFG_ONSET_COMPUTER_CORP,                         197,  esT("Onset Computer Corporation") )
MFG_MAP_ENTRY( MFG_SELFLY_BV,                                   198,  esT("Selfly BV") )
MFG_MAP_ENTRY( MFG_QUUPPA_OY,                                   199,  esT("Quuppa Oy.") )
MFG_MAP_ENTRY( MFG_GELO_INC,                                    200,  esT("GeLo Inc") )
MFG_MAP_ENTRY( MFG_EVLUMA,                                      201,  esT("Evluma") )
MFG_MAP_ENTRY( MFG_MC10,                                        202,  esT("MC10") )
MFG_MAP_ENTRY( MFG_BINAURIC_SE,                                 203,  esT("Binauric SE") )
MFG_MAP_ENTRY( MFG_BEATS_ELECTRONICS,                           204,  esT("Beats Electronics") )
MFG_MAP_ENTRY( MFG_MICROCHIP_TECH_INC,                          205,  esT("Microchip Technology Inc.") )
MFG_MAP_ENTRY( MFG_ELGATO_SYSTEMS_GMBH,                         206,  esT("Elgato Systems GmbH") )
MFG_MAP_ENTRY( MFG_ARCHOS_SA,                                   207,  esT("ARCHOS SA") )
MFG_MAP_ENTRY( MFG_DEXCOM,                                      208,  esT("Dexcom, Inc.") )
MFG_MAP_ENTRY( MFG_POLAR_ELECTRO_EUROPE_BV,                     209,  esT("Polar Electro Europe B.V.") )
MFG_MAP_ENTRY( MFG_DIALOG_SEMICONDUCTOR_BV,                     210,  esT("Dialog Semiconductor B.V.") )
MFG_MAP_ENTRY( MFG_TAIXINGBANG_TECHCO,                          211,  esT("Taixingbang Technology (HK) Co,. LTD.") )
MFG_MAP_ENTRY( MFG_KAWANTECH,                                   212,  esT("Kawantech") )
MFG_MAP_ENTRY( MFG_AUSTCO_COMMUNICATION_SYSTEMS,                213,  esT("Austco Communication Systems") )
MFG_MAP_ENTRY( MFG_TIMEX_GROUP_USA,                             214,  esT("Timex Group USA, Inc.") )
MFG_MAP_ENTRY( MFG_QUALCOMM_TECHNOLOGIES,                       215,  esT("Qualcomm Technologies, Inc.") )
MFG_MAP_ENTRY( MFG_QUALCOMM_CONNECTED_EXPERIENCES,              216,  esT("Qualcomm Connected Experiences, Inc.") )
MFG_MAP_ENTRY( MFG_VOYETRA_TURTLE_BEACH,                        217,  esT("Voyetra Turtle Beach") )
MFG_MAP_ENTRY( MFG_TXTR_GMBH,                                   218,  esT("txtr GmbH") )
MFG_MAP_ENTRY( MFG_BIOSENTRONICS,                               219,  esT("Biosentronics") )
MFG_MAP_ENTRY( MFG_PROCTERGAMBLE,                               220,  esT("Procter & Gamble") )
MFG_MAP_ENTRY( MFG_HOSIDEN_CORP,                                221,  esT("Hosiden Corporation") )
MFG_MAP_ENTRY( MFG_MUZIK_LLC,                                   222,  esT("Muzik LLC") )
MFG_MAP_ENTRY( MFG_MISFIT_WEARABLES_CORP,                       223,  esT("Misfit Wearables Corp") )
MFG_MAP_ENTRY( MFG_GOOGLE,                                      224,  esT("Google") )
MFG_MAP_ENTRY( MFG_DANLERS_LTD,                                 225,  esT("Danlers Ltd") )
MFG_MAP_ENTRY( MFG_SEMILINK_INC,                                226,  esT("Semilink Inc") )
MFG_MAP_ENTRY( MFG_INMUSIC_BRANDS,                              227,  esT("inMusic Brands, Inc") )
MFG_MAP_ENTRY( MFG_LS_RESEARCH_INC,                             228,  esT("L.S. Research Inc.") )
MFG_MAP_ENTRY( MFG_EDEN_SOFTWARE_CONSULTANTS_LTD,               229,  esT("Eden Software Consultants Ltd.") )
MFG_MAP_ENTRY( MFG_FRESHTEMP,                                   230,  esT("Freshtemp") )
MFG_MAP_ENTRY( MFG_KS_TECHNOLOGIES,                             231,  esT("KS Technologies") )
MFG_MAP_ENTRY( MFG_ACTS_TECHNOLOGIES,                           232,  esT("ACTS Technologies") )
MFG_MAP_ENTRY( MFG_VTRACK_SYSTEMS,                              233,  esT("Vtrack Systems") )
MFG_MAP_ENTRY( MFG_NIELSEN_KELLERMAN_COMPANY,                   234,  esT("Nielsen-Kellerman Company") )
MFG_MAP_ENTRY( MFG_SERVER_TECH,                                 235,  esT("Server Technology, Inc.") )
MFG_MAP_ENTRY( MFG_BIORESEARCH_ASSOCIATES,                      236,  esT("BioResearch Associates") )
MFG_MAP_ENTRY( MFG_JOLLY_LOGIC,                                 237,  esT("Jolly Logic, LLC") )
MFG_MAP_ENTRY( MFG_ABOVE_AVERAGE_OUTCOMES,                      238,  esT("Above Average Outcomes, Inc.") )
MFG_MAP_ENTRY( MFG_BITSPLITTERS_GMBH,                           239,  esT("Bitsplitters GmbH") )
MFG_MAP_ENTRY( MFG_PAYPAL,                                      240,  esT("PayPal, Inc.") )
MFG_MAP_ENTRY( MFG_WITRON_TECH_LIMITED,                         241,  esT("Witron Technology Limited") )
MFG_MAP_ENTRY( MFG_AETHER_THINGS_INC,                           242,  esT("Aether Things Inc. (formerly Morse Project Inc.)") )
MFG_MAP_ENTRY( MFG_KENT_DISPLAYS_INC,                           243,  esT("Kent Displays Inc.") )
MFG_MAP_ENTRY( MFG_NAUTILUS_INC,                                244,  esT("Nautilus Inc.") )
MFG_MAP_ENTRY( MFG_SMARTIFIER_OY,                               245,  esT("Smartifier Oy") )
MFG_MAP_ENTRY( MFG_ELCOMETER_LIMITED,                           246,  esT("Elcometer Limited") )
MFG_MAP_ENTRY( MFG_VSN_TECHNOLOGIES_INC,                        247,  esT("VSN Technologies Inc.") )
MFG_MAP_ENTRY( MFG_ACEUNI_CORP,                                 248,  esT("AceUni Corp., Ltd.") )
MFG_MAP_ENTRY( MFG_STICKNFIND,                                  249,  esT("StickNFind") )
MFG_MAP_ENTRY( MFG_CRYSTAL_CODE_AB,                             250,  esT("Crystal Code AB") )
MFG_MAP_ENTRY( MFG_KOUKAAM_AS,                                  251,  esT("KOUKAAM a.s.") )
MFG_MAP_ENTRY( MFG_DELPHI_CORP,                                 252,  esT("Delphi Corporation") )
MFG_MAP_ENTRY( MFG_VALENCETECH_LIMITED,                         253,  esT("ValenceTech Limited") )
MFG_MAP_ENTRY( MFG_RESERVED,                                    254,  esT("Reserved") )
MFG_MAP_ENTRY( MFG_TYPO_PRODUCTS,                               255,  esT("Typo Products, LLC") )
MFG_MAP_ENTRY( MFG_TOMTOM_INTERNATIONAL_BV,                     256,  esT("TomTom International BV") )
MFG_MAP_ENTRY( MFG_FUGOO,                                       257,  esT("Fugoo, Inc") )
MFG_MAP_ENTRY( MFG_KEISER_CORP,                                 258,  esT("Keiser Corporation") )
MFG_MAP_ENTRY( MFG_BANGOLUFSEN_AS,                              259,  esT("Bang & Olufsen A/S") )
MFG_MAP_ENTRY( MFG_PLUS_LOCATIONS_SYSTEMS_PTY_LTD,              260,  esT("PLUS Locations Systems Pty Ltd") )
MFG_MAP_ENTRY( MFG_UBIQUITOUS_COMPUTING_TECH_CORP,              261,  esT("Ubiquitous Computing Technology Corporation") )
MFG_MAP_ENTRY( MFG_INNOVATIVE_YACHTTER_SOLUTIONS,               262,  esT("Innovative Yachtter Solutions") )
MFG_MAP_ENTRY( MFG_WILLIAM_DEMANT_HOLDING_AS,                   263,  esT("William Demant Holding A/S") )
MFG_MAP_ENTRY( MFG_CHICONY_ELECTRONICS_CO,                      264,  esT("Chicony Electronics Co., Ltd.") )
MFG_MAP_ENTRY( MFG_ATUS_BV,                                     265,  esT("Atus BV") )
MFG_MAP_ENTRY( MFG_CODEGATE_LTD,                                266,  esT("Codegate Ltd.") )
MFG_MAP_ENTRY( MFG_ERI,                                         267,  esT("ERi, Inc.") )
MFG_MAP_ENTRY( MFG_TRANSDUCERS_DIRECT,                          268,  esT("Transducers Direct, LLC") )
MFG_MAP_ENTRY( MFG_FUJITSU_TEN_LIMITED,                         269,  esT("Fujitsu Ten Limited") )
MFG_MAP_ENTRY( MFG_AUDI_AG,                                     270,  esT("Audi AG") )
MFG_MAP_ENTRY( MFG_HISILICON_TECHNOLOGIES_CO,                   271,  esT("HiSilicon Technologies Co., Ltd.") )
MFG_MAP_ENTRY( MFG_NIPPON_SEIKI_CO,                             272,  esT("Nippon Seiki Co., Ltd.") )
MFG_MAP_ENTRY( MFG_STEELSERIES_APS,                             273,  esT("Steelseries ApS") )
MFG_MAP_ENTRY( MFG_VYZYBL_INC,                                  274,  esT("vyzybl Inc.") )
MFG_MAP_ENTRY( MFG_OPENBRAIN_TECHNOLOGIES,                      275,  esT("Openbrain Technologies, Co., Ltd.") )
MFG_MAP_ENTRY( MFG_XENSR,                                       276,  esT("Xensr") )
MFG_MAP_ENTRY( MFG_ESOLUTIONS,                                  277,  esT("E.solutions") )
MFG_MAP_ENTRY( MFG_1OAK_TECHNOLOGIES,                           278,  esT("1OAK Technologies") )
MFG_MAP_ENTRY( MFG_WIMOTO_TECHNOLOGIES_INC,                     279,  esT("Wimoto Technologies Inc") )
MFG_MAP_ENTRY( MFG_RADIUS_NETWORKS,                             280,  esT("Radius Networks, Inc.") )
MFG_MAP_ENTRY( MFG_WIZE_TECH_CO,                                281,  esT("Wize Technology Co., Ltd.") )
MFG_MAP_ENTRY( MFG_QUALCOMM_LABS,                               282,  esT("Qualcomm Labs, Inc.") )
MFG_MAP_ENTRY( MFG_ARUBA_NETWORKS,                              283,  esT("Aruba Networks") )
MFG_MAP_ENTRY( MFG_BAIDU,                                       284,  esT("Baidu") )
MFG_MAP_ENTRY( MFG_ARENDI_AG,                                   285,  esT("Arendi AG") )
MFG_MAP_ENTRY( MFG_SKODA_AUTO_AS,                               286,  esT("Skoda Auto a.s.") )
MFG_MAP_ENTRY( MFG_VOLKSWAGON_AG,                               287,  esT("Volkswagon AG") )
MFG_MAP_ENTRY( MFG_PORSCHE_AG,                                  288,  esT("Porsche AG") )
MFG_MAP_ENTRY( MFG_SINO_WEALTH_ELECTRONIC_LTD,                  289,  esT("Sino Wealth Electronic Ltd.") )
MFG_MAP_ENTRY( MFG_AIRTURN,                                     290,  esT("AirTurn, Inc.") )
MFG_MAP_ENTRY( MFG_KINSA,                                       291,  esT("Kinsa, Inc.") )
MFG_MAP_ENTRY( MFG_HID_GLOBAL,                                  292,  esT("HID Global") )
MFG_MAP_ENTRY( MFG_SEAT_ES,                                     293,  esT("SEAT es") )
MFG_MAP_ENTRY( MFG_PROMETHEAN_LTD,                              294,  esT("Promethean Ltd.") )
MFG_MAP_ENTRY( MFG_SALUTICA_ALLIED_SOLUTIONS,                   295,  esT("Salutica Allied Solutions") )
MFG_MAP_ENTRY( MFG_GPSI_GROUP_PTY_LTD,                          296,  esT("GPSI Group Pty Ltd") )
MFG_MAP_ENTRY( MFG_NIMBLE_DEVICES_OY,                           297,  esT("Nimble Devices Oy") )
MFG_MAP_ENTRY( MFG_CHANGZHOU_YONGSE_INFOTECH_CO,                298,  esT("Changzhou Yongse Infotech Co., Ltd") )
MFG_MAP_ENTRY( MFG_SPORTIQ,                                     299,  esT("SportIQ") )
MFG_MAP_ENTRY( MFG_TEMEC_INSTRUMENTS_BV,                        300,  esT("TEMEC Instruments B.V.") )
MFG_MAP_ENTRY( MFG_SONY_CORP,                                   301,  esT("Sony Corporation") )
MFG_MAP_ENTRY( MFG_ASSA_ABLOY,                                  302,  esT("ASSA ABLOY") )
MFG_MAP_ENTRY( MFG_CLARION_CO,                                  303,  esT("Clarion Co., Ltd.") )
MFG_MAP_ENTRY( MFG_WAREHOUSE_INNOVATIONS,                       304,  esT("Warehouse Innovations") )
MFG_MAP_ENTRY( MFG_CYPRESS_SEMICONDUCTOR_CORP,                  305,  esT("Cypress Semiconductor Corporation") )
MFG_MAP_ENTRY( MFG_MADS_INC,                                    306,  esT("MADS Inc") )
MFG_MAP_ENTRY( MFG_BLUE_MAESTRO_LIMITED,                        307,  esT("Blue Maestro Limited") )
MFG_MAP_ENTRY( MFG_RESOLUTION_PRODUCTS,                         308,  esT("Resolution Products, Inc.") )
MFG_MAP_ENTRY( MFG_AIREWEAR_LLC,                                309,  esT("Airewear LLC") )
MFG_MAP_ENTRY( MFG_ETC_SP_ZOO,                                  310,  esT("ETC sp. z.o.o.") )
MFG_MAP_ENTRY( MFG_PRESTIGIO_PLAZA_LTD,                         311,  esT("Prestigio Plaza Ltd.") )
MFG_MAP_ENTRY( MFG_NTEO_INC,                                    312,  esT("NTEO Inc.") )
MFG_MAP_ENTRY( MFG_FOCUS_SYSTEMS_CORP,                          313,  esT("Focus Systems Corporation") )
MFG_MAP_ENTRY( MFG_TENCENT_HOLDINGS_LIMITED,                    314,  esT("Tencent Holdings Limited") )
MFG_MAP_ENTRY( MFG_ALLEGION,                                    315,  esT("Allegion") )
MFG_MAP_ENTRY( MFG_MURATA_MANUFACURING_CO,                      316,  esT("Murata Manufacuring Co., Ltd.") )
MFG_MAP_ENTRY( MFG_NOD,                                         318,  esT("Nod, Inc.") )
MFG_MAP_ENTRY( MFG_BB_MANUFACTURING_COMPANY,                    319,  esT("B&B Manufacturing Company") )
MFG_MAP_ENTRY( MFG_ALPINE_ELECTRONICSCO,                        320,  esT("Alpine Electronics (China) Co., Ltd") )
MFG_MAP_ENTRY( MFG_FEDEX_SERVICES,                              321,  esT("FedEx Services") )
MFG_MAP_ENTRY( MFG_GRAPE_SYSTEMS_INC,                           322,  esT("Grape Systems Inc.") )
MFG_MAP_ENTRY( MFG_BKON_CONNECT,                                323,  esT("Bkon Connect") )
MFG_MAP_ENTRY( MFG_LINTECH_GMBH,                                324,  esT("Lintech GmbH") )
MFG_MAP_ENTRY( MFG_NOVATEL_WIRELESS,                            325,  esT("Novatel Wireless") )
MFG_MAP_ENTRY( MFG_CIRIGHT,                                     326,  esT("Ciright") )
MFG_MAP_ENTRY( MFG_MIGHTY_CAST,                                 327,  esT("Mighty Cast, Inc.") )
MFG_MAP_ENTRY( MFG_AMBIMAT_ELECTRONICS,                         328,  esT("Ambimat Electronics") )
MFG_MAP_ENTRY( MFG_PERYTONS_LTD,                                329,  esT("Perytons Ltd.") )
MFG_MAP_ENTRY( MFG_TIVOLI_AUDIO,                                330,  esT("Tivoli Audio, LLC") )
MFG_MAP_ENTRY( MFG_MASTER_LOCK,                                 331,  esT("Master Lock") )
MFG_MAP_ENTRY( MFG_MESH_NET_LTD,                                332,  esT("Mesh-Net Ltd") )
MFG_MAP_ENTRY( MFG_HUIZHOU_DESAY_SV_AUTOMOTIVE_CO,              333,  esT("Huizhou Desay SV Automotive CO., LTD.") )
MFG_MAP_ENTRY( MFG_TANGERINE,                                   334,  esT("Tangerine, Inc.") )
MFG_MAP_ENTRY( MFG_BW_GROUP_LTD,                                335,  esT("B&W Group Ltd.") )
MFG_MAP_ENTRY( MFG_PIONEER_CORP,                                336,  esT("Pioneer Corporation") )
MFG_MAP_ENTRY( MFG_ONBEEP,                                      337,  esT("OnBeep") )
MFG_MAP_ENTRY( MFG_VERNIER_SOFTWARETECH,                        338,  esT("Vernier Software & Technology") )
MFG_MAP_ENTRY( MFG_ROL_ERGO,                                    339,  esT("ROL Ergo") )
MFG_MAP_ENTRY( MFG_PEBBLE_TECH,                                 340,  esT("Pebble Technology") )
MFG_MAP_ENTRY( MFG_NETATMO,                                     341,  esT("NETATMO") )
MFG_MAP_ENTRY( MFG_ACCUMULATE_AB,                               342,  esT("Accumulate AB") )
MFG_MAP_ENTRY( MFG_ANHUI_HUAMI_INFORMATION_TECH_CO,             343,  esT("Anhui Huami Information Technology Co., Ltd.") )
MFG_MAP_ENTRY( MFG_INMITE_SRO,                                  344,  esT("Inmite s.r.o.") )
MFG_MAP_ENTRY( MFG_CHEFSTEPS,                                   345,  esT("ChefSteps, Inc.") )
MFG_MAP_ENTRY( MFG_MICAS_AG,                                    346,  esT("micas AG") )
MFG_MAP_ENTRY( MFG_BIOMEDICAL_RESEARCH_LTD,                     347,  esT("Biomedical Research Ltd.") )
MFG_MAP_ENTRY( MFG_PITIUS_TEC_SL,                               348,  esT("Pitius Tec S.L.") )
MFG_MAP_ENTRY( MFG_ESTIMOTE,                                    349,  esT("Estimote, Inc.") )
MFG_MAP_ENTRY( MFG_UNIKEY_TECHNOLOGIES,                         350,  esT("Unikey Technologies, Inc.") )
MFG_MAP_ENTRY( MFG_TIMER_CAP_CO,                                351,  esT("Timer Cap Co.") )
MFG_MAP_END

#undef MFG_MAP_BEGIN
#undef MFG_MAP_ENTRY
#undef MFG_MAP_END
