// EsScriptCompilerRuleNames.def file
// rule names must go here
//

GRAMMAR_RULE(value)
GRAMMAR_RULE(simpleVal)
GRAMMAR_RULE(boolVal)
GRAMMAR_RULE(intVal)
GRAMMAR_RULE(floatVal)
GRAMMAR_RULE(strVal)
GRAMMAR_RULE(arrayVal)
// identifier
GRAMMAR_RULE(ident)	
// lhs|rhs 
GRAMMAR_RULE(idxAcc)
GRAMMAR_RULE(fieldAcc)
GRAMMAR_RULE(propAcc)
GRAMMAR_RULE(attrAcc)
GRAMMAR_RULE(objMethodCall)
GRAMMAR_RULE(lrhs)
// operators	
GRAMMAR_RULE(opAssign)
GRAMMAR_RULE(opIncDec)
GRAMMAR_RULE(opLogical)
GRAMMAR_RULE(opBitwise)
GRAMMAR_RULE(opEqNeq)
GRAMMAR_RULE(opCmp)
GRAMMAR_RULE(opSh)
GRAMMAR_RULE(opAddSub)
GRAMMAR_RULE(opMulDiv)
GRAMMAR_RULE(opUnary)
// expressions
GRAMMAR_RULE(expr)
GRAMMAR_RULE(exprBitwise)
GRAMMAR_RULE(exprEqNeq)
GRAMMAR_RULE(exprCmp)
GRAMMAR_RULE(exprSh)
GRAMMAR_RULE(exprAddSub)
GRAMMAR_RULE(exprMulDiv)
GRAMMAR_RULE(exprUnary)
GRAMMAR_RULE(exprIncDec)
GRAMMAR_RULE(exprIncDecPfx)
GRAMMAR_RULE(exprFuncCall)
GRAMMAR_RULE(exprObjCtrCall)
GRAMMAR_RULE(exprStaticCall)
GRAMMAR_RULE(exprCall)
GRAMMAR_RULE(exprAtom)
GRAMMAR_RULE(exprAssign)
GRAMMAR_RULE(exprInitAsn)
GRAMMAR_RULE(exprForInit)
GRAMMAR_RULE(exprForCheck)
GRAMMAR_RULE(exprForCnt)
GRAMMAR_RULE(exprWhileCheck)
// statements
GRAMMAR_RULE(script)
GRAMMAR_RULE(stmt)
GRAMMAR_RULE(stmtAssign)
GRAMMAR_RULE(stmtIncDec)
GRAMMAR_RULE(stmtConstDecl)
GRAMMAR_RULE(stmtVarDecl)
GRAMMAR_RULE(stmtReturn)
GRAMMAR_RULE(stmtFuncDecl)
GRAMMAR_RULE(stmtAttributeDecl)
GRAMMAR_RULE(stmtAttributeList)
GRAMMAR_RULE(stmtObjFldDecl)
GRAMMAR_RULE(stmtObjPlainFldDecl)
GRAMMAR_RULE(stmtObjArrayFldDecl)
GRAMMAR_RULE(stmtObjDeclBlock)
GRAMMAR_RULE(stmtObjDecl)
GRAMMAR_RULE(stmtObjMethodDecl)
GRAMMAR_RULE(stmtObjCtorDecl)
GRAMMAR_RULE(stmtObjDtorDecl)
GRAMMAR_RULE(stmtCall)
GRAMMAR_RULE(stmtLrhs)
GRAMMAR_RULE(stmtElse)
GRAMMAR_RULE(stmtIf)
GRAMMAR_RULE(stmtFor)
GRAMMAR_RULE(stmtWhile)
GRAMMAR_RULE(stmtDoWhile)
GRAMMAR_RULE(stmtBreak)
GRAMMAR_RULE(stmtContinue)
GRAMMAR_RULE(stmtLabel)
GRAMMAR_RULE(stmtGoto)
GRAMMAR_RULE(stmtNoop)
GRAMMAR_RULE(stmtList)
GRAMMAR_RULE(stmtBlock)

#undef GRAMMAR_RULE