// supplementary file containing reflected method declaration entries
// must not be used directly in project build. instead, it's included
// and preprocessed in Reflection.cpp & Reflection.h files
//
// macros templates for copy-paste implementation
//
//#define REFL_METHOD_ENTRIES_BEGIN
//#define REFL_METHOD_ENTRY0( RetVal )
//#define REFL_METHOD_ENTRY1( RetVal, Param1 )
//#define REFL_METHOD_ENTRY2( RetVal, Param1, Param2 )
//#define REFL_METHOD_ENTRY3( RetVal, Param1, Param2, Param3 )
//#define REFL_METHOD_ENTRY4( RetVal, Param1, Param2, Param3, Param4 )
//#define REFL_METHOD_ENTRY5( RetVal, Param1, Param2, Param3, Param4, Param5 )
//#define REFL_METHOD_ENTRY6( RetVal, Param1, Param2, Param3, Param4, Param5, Param6 )
//#define REFL_METHOD_ENTRY7( RetVal, Param1, Param2, Param3, Param4, Param5, Param6, Param7 )
//#define REFL_METHOD_ENTRY_NR0
//#define REFL_METHOD_ENTRY_NR1( Param1 )
//#define REFL_METHOD_ENTRY_NR2( Param1, Param2 )
//#define REFL_METHOD_ENTRY_NR3( Param1, Param2, Param3 )
//#define REFL_METHOD_ENTRY_NR4( Param1, Param2, Param3, Param4 )
//#define REFL_METHOD_ENTRY_NR5( Param1, Param2, Param3, Param4, Param5 )
//#define REFL_METHOD_ENTRY_NR6( Param1, Param2, Param3, Param4, Param5, Param6 )
//#define REFL_METHOD_ENTRY_NR7( Param1, Param2, Param3, Param4, Param5, Param6, Param7 )
//#define REFL_CONST_METHOD_ENTRY0( RetVal )
//#define REFL_CONST_METHOD_ENTRY1( RetVal, Param1 )
//#define REFL_CONST_METHOD_ENTRY2( RetVal, Param1, Param2 )
//#define REFL_CONST_METHOD_ENTRY3( RetVal, Param1, Param2, Param3 )
//#define REFL_CONST_METHOD_ENTRY4( RetVal, Param1, Param2, Param3, Param4 )
//#define REFL_CONST_METHOD_ENTRY5( RetVal, Param1, Param2, Param3, Param4, Param5 )
//#define REFL_CONST_METHOD_ENTRY6( RetVal, Param1, Param2, Param3, Param4, Param5, Param6 )
//#define REFL_CONST_METHOD_ENTRY7( RetVal, Param1, Param2, Param3, Param4, Param5, Param6, Param7 )
//#define REFL_CONST_METHOD_ENTRY_NR0
//#define REFL_CONST_METHOD_ENTRY_NR1( Param1 )
//#define REFL_CONST_METHOD_ENTRY_NR2( Param1, Param2 )
//#define REFL_CONST_METHOD_ENTRY_NR3( Param1, Param2, Param3 )
//#define REFL_CONST_METHOD_ENTRY_NR4( Param1, Param2, Param3, Param4 )
//#define REFL_CONST_METHOD_ENTRY_NR5( Param1, Param2, Param3, Param4, Param5 )
//#define REFL_CONST_METHOD_ENTRY_NR6( Param1, Param2, Param3, Param4, Param5, Param6 )
//#define REFL_CONST_METHOD_ENTRY_NR7( Param1, Param2, Param3, Param4, Param5, Param6, Param7 )
//#define REFL_METHOD_ENTRIES_END
//#define REFL_CLASS_METHOD_ENTRIES_BEGIN
//#define REFL_CLASS_METHOD_ENTRY0( RetVal )
//#define REFL_CLASS_METHOD_ENTRY1( RetVal, Param1 )
//#define REFL_CLASS_METHOD_ENTRY2( RetVal, Param1, Param2 )
//#define REFL_CLASS_METHOD_ENTRY3( RetVal, Param1, Param2, Param3 )
//#define REFL_CLASS_METHOD_ENTRY4( RetVal, Param1, Param2, Param3, Param4 )
//#define REFL_CLASS_METHOD_ENTRY5( RetVal, Param1, Param2, Param3, Param4, Param5 )
//#define REFL_CLASS_METHOD_ENTRY6( RetVal, Param1, Param2, Param3, Param4, Param5, Param6 )
//#define REFL_CLASS_METHOD_ENTRY7( RetVal, Param1, Param2, Param3, Param4, Param5, Param6, Param7 )
//#define REFL_CLASS_METHOD_ENTRY_NR0
//#define REFL_CLASS_METHOD_ENTRY_NR1( Param1 )
//#define REFL_CLASS_METHOD_ENTRY_NR2( Param1, Param2 )
//#define REFL_CLASS_METHOD_ENTRY_NR3( Param1, Param2, Param3 )
//#define REFL_CLASS_METHOD_ENTRY_NR4( Param1, Param2, Param3, Param4 )
//#define REFL_CLASS_METHOD_ENTRY_NR5( Param1, Param2, Param3, Param4, Param5 )
//#define REFL_CLASS_METHOD_ENTRY_NR6( Param1, Param2, Param3, Param4, Param5, Param6 )
//#define REFL_CLASS_METHOD_ENTRY_NR7( Param1, Param2, Param3, Param4, Param5, Param6, Param7 )
//#define REFL_CLASS_METHOD_ENTRIES_END
//#include <core/Reflection.hxx>

// reflected member functions go here. NB! add new definitions at the end of list only!
//                              RetVal                      Param1              Param2        Param3        Param4        Param5        Param6      Param7
REFL_METHOD_ENTRIES_BEGIN
  REFL_METHOD_ENTRY_NR0
  REFL_METHOD_ENTRY0(            bool)
  REFL_CONST_METHOD_ENTRY0(      bool)
  REFL_CONST_METHOD_ENTRY0(      long)
  REFL_METHOD_ENTRY_NR1(                                    cr_long )
  REFL_CONST_METHOD_ENTRY0(      EsString)
  REFL_METHOD_ENTRY_NR1(                                    cr_EsString )
  REFL_METHOD_ENTRY1(            EsString,                    long)
  REFL_METHOD_ENTRY_NR1(                                    cr_bool)
  REFL_METHOD_ENTRY3(            long,                        cp_void,            long,          long)
  REFL_METHOD_ENTRY3(            long,                        p_void,              long,          long)
  REFL_METHOD_ENTRY_NR1(                                    p_void)
  REFL_CONST_METHOD_ENTRY1(      EsString,                    long)
  REFL_CONST_METHOD_ENTRY2(      EsString,                    long,                bool)
  REFL_CONST_METHOD_ENTRY_NR0
  REFL_CONST_METHOD_ENTRY0(      EsBaseIntfPtr)
  REFL_CONST_METHOD_ENTRY0(      double)
  REFL_CONST_METHOD_ENTRY0(      EsVariant)
  REFL_CONST_METHOD_ENTRY0(      EsBinBuffer)
  REFL_CONST_METHOD_ENTRY1(      EsVariant,                  long)
  REFL_METHOD_ENTRY1(            bool,                        long)
  REFL_CONST_METHOD_ENTRY1(      bool,                        long)
  REFL_METHOD_ENTRY2(            ulong,                      cr_EsBinBuffer,      ulong)
  REFL_METHOD_ENTRY2(            EsBinBuffer,                ulong,              ulong)
  REFL_METHOD_ENTRY_NR1(                                    cr_EsVariant)
  REFL_CONST_METHOD_ENTRY1(      bool,                        cr_EsString)
  REFL_METHOD_ENTRY_NR1(                                    long)
  REFL_METHOD_ENTRY0(            EsVariant)
  REFL_METHOD_ENTRY0(            ulong)
  REFL_METHOD_ENTRY1(            bool,                        cr_EsVariant)
  REFL_METHOD_ENTRY_NR1(                                    ulong)
  REFL_CONST_METHOD_ENTRY0(      ulong)
  REFL_CONST_METHOD_ENTRY1(      EsString,                    ulong)
  REFL_METHOD_ENTRY_NR1(                                    cr_ulong)  
  REFL_METHOD_ENTRY0(            EsBinBuffer)
  REFL_CONST_METHOD_ENTRY1(      bool,                        cr_EsVariant)
  REFL_CONST_METHOD_ENTRY1(      int,                        cr_EsVariant)
  REFL_METHOD_ENTRY1(            esU8,                        esU16)
  REFL_METHOD_ENTRY1(            esI8,                        esU16)
  REFL_METHOD_ENTRY1(            esU16,                      esU16)
  REFL_METHOD_ENTRY1(            esI16,                      esU16)
  REFL_METHOD_ENTRY1(            esU32,                      esU16)
  REFL_METHOD_ENTRY1(            esI32,                      esU16)
  REFL_METHOD_ENTRY1(            esU64,                      esU16)
  REFL_METHOD_ENTRY1(            esI64,                      esU16)
  REFL_METHOD_ENTRY1(            esF,                        esU16)
  REFL_METHOD_ENTRY1(            esBL,                        esU16)
  REFL_METHOD_ENTRY1(            esDT,                        esU16)
  REFL_METHOD_ENTRY1(            EsBinBuffer,                esU16)
  REFL_METHOD_ENTRY_NR1(                                    esU16)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              esBA)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              esU16)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              esF)
  REFL_METHOD_ENTRY2(            esBL,                        esU16,              esDT)
  REFL_METHOD_ENTRY2(            EsBinBuffer,                esU16,              esU16)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              esU8)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              esU32)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              esBL)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              esU8,              esF)
  REFL_METHOD_ENTRY2(            esF,                        esU16,              esU8)
  REFL_METHOD_ENTRY2(            esU16,                      esU16,              esBA)
  REFL_METHOD_ENTRY3(            esU16,                      esU16,              esBA,              esBL)
  REFL_METHOD_ENTRY2(            EsBinBuffer,                esU16,              esBA)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              esU8,              esBA)
  REFL_METHOD_ENTRY2(            bool,                        ulong,              bool)
  REFL_METHOD_ENTRY1(            bool,                        ulong)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsString,        bool)
  REFL_METHOD_ENTRY2(            EsBinBuffer,                esU16,              esU32)
  REFL_METHOD_ENTRY3(            EsBinBuffer,                esU16,              esU32,             esU32)
  REFL_METHOD_ENTRY2(            EsVariant,                  ulong,              ulong)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              esU32,            esBA)
  REFL_METHOD_ENTRY2(            EsBinBuffer,                esU16,              esU8)
  REFL_CONST_METHOD_ENTRY0(      int)
  REFL_CONST_METHOD_ENTRY1(      EsVariant,                  cr_EsVariant)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsVariant,        cr_EsVariant)
  REFL_METHOD_ENTRY3(            ulong,                      cr_EsBinBuffer,      ulong,            cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY3(            EsBinBuffer,                ulong,              ulong,            cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esU8,                        esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esI8,                        esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esU16,                      esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esI16,                      esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esU32,                      esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esI32,                      esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esU64,                      esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esI64,                      esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esF,                        esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esBL,                        esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            esDT,                        esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            EsBinBuffer,                esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY_NR2(                                    esU16,              cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              cr_EsBaseIntfPtr, esBA)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              cr_EsBaseIntfPtr,  esU16)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              cr_EsBaseIntfPtr,  esF)
  REFL_METHOD_ENTRY3(            esBL,                        esU16,              cr_EsBaseIntfPtr, esDT)
  REFL_METHOD_ENTRY3(            EsBinBuffer,                esU16,              cr_EsBaseIntfPtr,  esU16)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              cr_EsBaseIntfPtr,  esU8)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              cr_EsBaseIntfPtr,  esU32)
  REFL_METHOD_ENTRY_NR3(                                    esU16,              cr_EsBaseIntfPtr,  esBL)
  REFL_METHOD_ENTRY_NR4(                                    esU16,              cr_EsBaseIntfPtr,  esU8,          esF)
  REFL_METHOD_ENTRY3(            esF,                        esU16,              cr_EsBaseIntfPtr,  esU8)
  REFL_METHOD_ENTRY3(            esU16,                      esU16,              cr_EsBaseIntfPtr,  esBA)
  REFL_METHOD_ENTRY4(            esU16,                      esU16,              cr_EsBaseIntfPtr,  esBA,          esBL)
  REFL_METHOD_ENTRY3(            EsBinBuffer,                esU16,              cr_EsBaseIntfPtr,  esBA)
  REFL_METHOD_ENTRY_NR4(                                    esU16,              cr_EsBaseIntfPtr,  esU8,          esBA)
  REFL_METHOD_ENTRY3(            EsBinBuffer,                esU16,              cr_EsBaseIntfPtr,  esU32)
  REFL_METHOD_ENTRY4(            EsBinBuffer,                esU16,              cr_EsBaseIntfPtr,  esU32,         esU32)
  REFL_METHOD_ENTRY_NR4(                                    esU16,              cr_EsBaseIntfPtr,  esU32,        esBA)
  REFL_METHOD_ENTRY3(            EsBinBuffer,                esU16,              cr_EsBaseIntfPtr,  esU8)
  REFL_METHOD_ENTRY1(            bool,                        cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            bool,                        cr_EsBaseIntfPtr,    ulong)
  REFL_METHOD_ENTRY3(            EsVariant,                  cr_EsBaseIntfPtr,    ulong,            ulong)
  REFL_METHOD_ENTRY3(            bool,                        cr_EsBaseIntfPtr,    ulong,            bool)
  REFL_METHOD_ENTRY1(            EsVariant,                  cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY1(            ulong,                      cr_EsBaseIntfPtr)  
  REFL_METHOD_ENTRY_NR1(                                    cr_EsBaseIntfPtr)
  REFL_METHOD_ENTRY2(            bool,                        cr_EsBaseIntfPtr,    cr_EsVariant)  
  REFL_METHOD_ENTRY_NR2(                                    cr_EsBaseIntfPtr,    ulong)
  REFL_METHOD_ENTRY1(            EsBinBuffer,                cr_EsBaseIntfPtr)
  REFL_CONST_METHOD_ENTRY1(      ulong,                      ulong)
  REFL_CONST_METHOD_ENTRY0(      EsStringArray)
  REFL_CONST_METHOD_ENTRY1(      EsVariant,                  cr_EsString)
  REFL_CONST_METHOD_ENTRY1(      EsString,                    cr_EsString)
  REFL_CONST_METHOD_ENTRY1(      cr_EsVariant,                cr_EsString)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsString,        cr_EsVariant)
  REFL_METHOD_ENTRY_NR1(                                    cr_EsStringArray)
  REFL_CONST_METHOD_ENTRY1(      EsString,                    cr_EsVariant)
  REFL_CONST_METHOD_ENTRY1(      ulong,                      cr_EsVariant)
  REFL_CONST_METHOD_ENTRY0(      cr_EsString)
  REFL_CONST_METHOD_ENTRY0(      ullong)
  REFL_CONST_METHOD_ENTRY0(      llong)
  REFL_METHOD_ENTRY1(            llong,                      ullong)
  REFL_METHOD_ENTRY1(            llong,                      llong)
  REFL_METHOD_ENTRY1(            ullong,                      cr_EsVariant)
  REFL_METHOD_ENTRY2(            bool,                        cr_EsString,        bool)
  REFL_CONST_METHOD_ENTRY_NR1(                              cr_EsString)
  REFL_METHOD_ENTRY_NR1(                                    cr_EsBinBuffer)
  REFL_CONST_METHOD_ENTRY1(      EsBaseIntfPtr,              cr_EsString)
  REFL_CONST_METHOD_ENTRY0(      esU8)
  REFL_CONST_METHOD_ENTRY0(      esU16)
  REFL_CONST_METHOD_ENTRY0(      esU32)
  REFL_CONST_METHOD_ENTRY1(      EsStringArray,              cr_EsString)
  REFL_CONST_METHOD_ENTRY2(      EsVariant,                  cr_EsString,        cr_EsVariant)
  REFL_CONST_METHOD_ENTRY3(      EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant)
  REFL_CONST_METHOD_ENTRY4(      EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,  cr_EsVariant)
  REFL_CONST_METHOD_ENTRY5(      EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_CONST_METHOD_ENTRY6(      EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsBaseIntfPtr,   cr_EsVariant)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsString,        cr_EsString)
  REFL_CONST_METHOD_ENTRY2(      EsVariant,                  cr_EsVariant,        cr_EsVariant)
  REFL_METHOD_ENTRY0(            EsBaseIntfPtr)
  REFL_CONST_METHOD_ENTRY_NR1(                              cr_EsBaseIntfPtr)
  REFL_CONST_METHOD_ENTRY0(      cr_EsVariant)
  REFL_METHOD_ENTRY_NR5(                                    esU16,              cr_EsBaseIntfPtr,  esU8,        esU8,        esU16)
  REFL_METHOD_ENTRY_NR4(                                    esU16,              esU8,              esU8,        esU16)
  REFL_METHOD_ENTRY1(            EsVariant,                  ulong)
  REFL_METHOD_ENTRY2(            bool,                        cr_EsVariant,        ulong)
  REFL_METHOD_ENTRY2(            bool,                        cr_EsString,        ulong)
  REFL_CONST_METHOD_ENTRY1(      EsVariant,                  ulong)
  REFL_METHOD_ENTRY2(            long,                        cr_EsString,        ulong)
  REFL_METHOD_ENTRY1(            long,                        cr_EsString)
  REFL_CONST_METHOD_ENTRY2(      bool,                        cr_EsString,        ulong)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsString,        long)
  REFL_METHOD_ENTRY_NR2(                                    long,                cr_EsString)
  REFL_METHOD_ENTRY_NR1(                                    bool)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsString,        ulong)
  REFL_METHOD_ENTRY1(            EsString,                    cr_EsString)
  REFL_METHOD_ENTRY2(            EsString,                    cr_EsString,        ulong)
  REFL_METHOD_ENTRY_NR3(                                    cr_EsString,        cr_EsVariant,      cr_EsString)
  REFL_METHOD_ENTRY1(            EsVariant,                  cr_EsString)
  REFL_METHOD_ENTRY2(            EsVariant,                  cr_EsString,        cr_EsVariant)
  REFL_METHOD_ENTRY3(            EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant)
  REFL_METHOD_ENTRY4(            EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,    cr_EsVariant)
  REFL_METHOD_ENTRY5(            EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,    cr_EsVariant,  cr_EsVariant)
  REFL_METHOD_ENTRY6(            EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,    cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_METHOD_ENTRY1(            bool,                        cr_EsString)
  REFL_CONST_METHOD_ENTRY1(      EsBinBuffer,                bool)
  REFL_METHOD_ENTRY_NR2(                                    cr_EsBinBuffer,      bool)
  REFL_METHOD_ENTRY_NR3(                                    cr_EsString,        bool,              cr_EsString)
  REFL_METHOD_ENTRY3(            EsBaseIntfPtr,              cr_EsString,        cr_EsString,      cr_EsString)
  REFL_METHOD_ENTRY1(            EsVariant,                  cr_EsVariant)
  REFL_METHOD_ENTRY2(            EsVariant,                  cr_EsVariant,        cr_EsVariant)
  REFL_METHOD_ENTRY3(            EsVariant,                  cr_EsVariant,        cr_EsVariant,      cr_EsVariant)
  REFL_METHOD_ENTRY4(            EsVariant,                  cr_EsVariant,        cr_EsVariant,      cr_EsVariant,    cr_EsVariant)
  REFL_METHOD_ENTRY5(            EsVariant,                  cr_EsVariant,        cr_EsVariant,      cr_EsVariant,    cr_EsVariant,  cr_EsVariant)
  REFL_METHOD_ENTRY6(            EsVariant,                  cr_EsVariant,        cr_EsVariant,      cr_EsVariant,    cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_METHOD_ENTRY0(            long)
  REFL_METHOD_ENTRY0(            llong)
  REFL_METHOD_ENTRY0(            ullong)
  REFL_METHOD_ENTRY0(            EsString)
  REFL_METHOD_ENTRY1(            ullong,                      long)
  REFL_METHOD_ENTRY1(            ullong,                      ulong)
  REFL_METHOD_ENTRY1(            ullong,                      llong)
  REFL_METHOD_ENTRY1(            ullong,                      ullong)
  REFL_METHOD_ENTRY1(            ullong,                      cr_EsString)
  REFL_METHOD_ENTRY1(            ullong,                      cr_EsBinBuffer)
  REFL_METHOD_ENTRY0(            esDT)
  REFL_METHOD_ENTRY1(            bool,                        esDT)
  REFL_CONST_METHOD_ENTRY1(      EsVariant,                  llong )
  REFL_METHOD_ENTRY_NR3(                                    cr_EsString,        ulong,            cr_EsVariant )
  REFL_METHOD_ENTRY_NR2(                                    ulong,              cr_EsVariant )
  REFL_CONST_METHOD_ENTRY1(      bool,                        ulong)
  REFL_METHOD_ENTRY_NR3(                                    cr_EsBinBuffer,      ulong,            ulong )
  REFL_CONST_METHOD_ENTRY2(      bool,                        cr_EsString,        cr_EsString )
  REFL_CONST_METHOD_ENTRY2(      EsVariant,                  cr_EsString,        cr_EsString )
  REFL_CONST_METHOD_ENTRY2(      EsString,                    ulong,              cr_EsString )
  REFL_METHOD_ENTRY_NR3(                                     cr_EsString,        cr_EsVariant,      cr_EsVariant )
  REFL_METHOD_ENTRY1(            EsBaseIntfPtr,              cr_EsString )
  REFL_METHOD_ENTRY2(            EsBaseIntfPtr,              cr_EsString,        cr_EsVariant )
  REFL_METHOD_ENTRY3(            EsBaseIntfPtr,              cr_EsString,        cr_EsVariant,      cr_EsVariant )
  REFL_METHOD_ENTRY4(            EsBaseIntfPtr,              cr_EsString,        cr_EsVariant,      cr_EsVariant,      cr_EsVariant )
  REFL_METHOD_ENTRY5(            EsBaseIntfPtr,              cr_EsString,        cr_EsVariant,      cr_EsVariant,      cr_EsVariant,  cr_EsVariant )
  REFL_METHOD_ENTRY6(            EsBaseIntfPtr,              cr_EsString,        cr_EsVariant,      cr_EsVariant,      cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_METHOD_ENTRY_NR3(                                     cr_EsString,        cr_EsString,      ulong )
  REFL_METHOD_ENTRY1(            ulong,                      ulong )
  REFL_METHOD_ENTRY_NR2(                                    cr_EsString,        cr_EsBaseIntfPtr )
  REFL_METHOD_ENTRY3(            EsBinBuffer,                cr_EsString,        bool,              cr_EsString )
  REFL_CONST_METHOD_ENTRY2(      EsStringArray,              cr_EsString,        cr_EsString )
  REFL_CONST_METHOD_ENTRY3(      bool,                        cr_EsString,        cr_EsString,      cr_EsString )
  REFL_CONST_METHOD_ENTRY3(      EsVariant,                  cr_EsString,        cr_EsString,      cr_EsString )
  REFL_CONST_METHOD_ENTRY2(      EsString,                    cr_EsString,        cr_EsString )
  REFL_CONST_METHOD_ENTRY7(      EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,      cr_EsVariant,  cr_EsVariant,  cr_EsVariant, cr_EsVariant)
  REFL_METHOD_ENTRY7(            EsVariant,                  cr_EsString,        cr_EsVariant,      cr_EsVariant,      cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_METHOD_ENTRY_NR1(                                    double )
  REFL_CONST_METHOD_ENTRY1(     double,                     ulong )
  REFL_METHOD_ENTRY_NR2(                                    ulong,              double )
  REFL_METHOD_ENTRY_NR1(                                    cr_double )
  REFL_METHOD_ENTRY_NR2(                                    double,             double )
  REFL_CONST_METHOD_ENTRY1(     double,                     double )
  REFL_METHOD_ENTRY_NR2(                                    cr_EsVariant,       ulong )
  REFL_METHOD_ENTRY_NR3(                                    cr_EsVariant,       cr_EsVariant,     ulong )
  REFL_METHOD_ENTRY_NR3(                                    cr_EsVariant,       ulong,            cr_EsVariant )
  REFL_METHOD_ENTRY_NR4(                                    cr_EsVariant,       cr_EsVariant,     ulong,            cr_EsVariant )
  REFL_CONST_METHOD_ENTRY1(      cr_EsVariant,                cr_EsVariant )
  REFL_CONST_METHOD_ENTRY2(      cr_EsVariant,                cr_EsVariant,        cr_EsVariant )
  REFL_CONST_METHOD_ENTRY_NR2(                              ulong,              cr_EsVariant )
  REFL_CONST_METHOD_ENTRY1(     EsString,                   bool )
  REFL_METHOD_ENTRY1(           bool,                       cr_EsBinBuffer )
  REFL_METHOD_ENTRY5(           bool,                       cr_EsBinBuffer,     double,           double,           bool,         bool )
  REFL_METHOD_ENTRY_NR1(                                    cr_ullong )
  REFL_CONST_METHOD_ENTRY_NR1(                              cr_EsVariant )
  REFL_METHOD_ENTRY_NR3(                                    cr_EsVariant,       cr_EsVariant,     cr_EsVariant )
  REFL_METHOD_ENTRY_NR4(                                    cr_EsVariant,       cr_EsVariant,     cr_EsVariant,     cr_EsVariant )
  REFL_METHOD_ENTRY2(           bool,                       esU16,              bool )
  REFL_METHOD_ENTRY3(           esU32,                      esU16,              cr_EsBinBuffer,   esU32 )
  REFL_METHOD_ENTRY2(           esU32,                      cr_EsBinBuffer,     esU32 )
  REFL_METHOD_ENTRY2(           EsBinBuffer,                esU32,              esU32 )
  REFL_METHOD_ENTRY2(           EsBinBuffer,                cr_EsBinBuffer,     esU32 )
  REFL_CONST_METHOD_ENTRY0(     byte)
  REFL_METHOD_ENTRY_NR1(                                    cr_byte )
  REFL_METHOD_ENTRY1(           bool,                       bool )
  REFL_CONST_METHOD_ENTRY3(     EsStringArray,              cr_EsString,        cr_EsString,      cr_EsString)
  REFL_METHOD_ENTRY_NR4(                                    esU16,              esU32,            esU32,            esBA)
  REFL_METHOD_ENTRY_NR5(                                    esU16,              esU32,            esU32,            esU32,        esBA)
  REFL_METHOD_ENTRY3(           esU32,                      esU16,              esU32,            esBA)
  REFL_METHOD_ENTRY_NR1(                                    esU8)
  REFL_METHOD_ENTRY_NR1(                                    esU32)
REFL_METHOD_ENTRIES_END

// reflected class functions go here. NB! add new definitions at the end of list only!
REFL_CLASS_METHOD_ENTRIES_BEGIN
  REFL_CLASS_METHOD_ENTRY_NR0
  REFL_CLASS_METHOD_ENTRY0(      EsBaseIntfPtr)
  REFL_CLASS_METHOD_ENTRY0(      EsVariant)  
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsBaseIntfPtr,   long)
  REFL_CLASS_METHOD_ENTRY4(      ulong,                      ulong,              ulong,        bool,          ulong)
  REFL_CLASS_METHOD_ENTRY_NR1(                              cr_EsString )
  REFL_CLASS_METHOD_ENTRY_NR2(                              cr_EsString,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR3(                              cr_EsString,        cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR4(                              cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR5(                              cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR6(                              cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      EsString,                    cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      ulong,                      cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsVariant,        ulong)
  REFL_CLASS_METHOD_ENTRY_NR3(                              cr_EsVariant,        ulong,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR1(                              cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      bool,                        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY0(      EsStringArray )
  REFL_CLASS_METHOD_ENTRY1(      EsStringArray,              cr_EsString )
  REFL_CLASS_METHOD_ENTRY1(      EsBinBuffer,                cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      esU8,                        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      long,                        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      llong,                      cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      ullong,                      cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      double,                      cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsVariant,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      EsString,                    cr_EsString )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              ulong,              cr_EsString)
  REFL_CLASS_METHOD_ENTRY2(      EsString,                    cr_EsString,        cr_EsVariant)
  REFL_CLASS_METHOD_ENTRY3(      EsString,                    cr_EsString,        cr_EsVariant,  cr_EsVariant)
  REFL_CLASS_METHOD_ENTRY4(      EsString,                    cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_CLASS_METHOD_ENTRY5(      EsString,                    cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_CLASS_METHOD_ENTRY6(      EsString,                    cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant)
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              cr_EsString )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  cr_EsBinBuffer )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  esU8 )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsBinBuffer,      esU8 )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  esU16 )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsBinBuffer,      esU16 )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  esU32 )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsBinBuffer,      esU32 )
  REFL_CLASS_METHOD_ENTRY3(      EsVariant,                  cr_EsVariant,        long,          long )
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              cr_EsBaseIntfPtr)
  REFL_CLASS_METHOD_ENTRY4(      EsVariant,                  cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      EsBinBuffer,                cr_EsString )
  REFL_CLASS_METHOD_ENTRY1(      EsString,                    cr_EsBinBuffer )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsString,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY2(      long,                        cr_EsVariant,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(      long,                        long )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  ulong )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  ulong,              ulong )
  REFL_CLASS_METHOD_ENTRY_NR2(                              cr_EsVariant,        ulong )
  REFL_CLASS_METHOD_ENTRY_NR3(                              cr_EsVariant,        cr_EsVariant, ulong )
  REFL_CLASS_METHOD_ENTRY2(      EsVariant,                  cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY_NR1(                              ulong )
  REFL_CLASS_METHOD_ENTRY2(      EsString,                    cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY2(      long,                        cr_EsString,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY4(      EsString,                    cr_EsStringArray,    cr_EsString,  cr_EsString,  cr_EsString)
  REFL_CLASS_METHOD_ENTRY2(      bool,                        cr_EsVariant,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              esU8 )
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              esU16 )
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              esU32 )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              cr_EsBinBuffer,      esU8 )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              cr_EsBinBuffer,      esU16 )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              cr_EsBinBuffer,      esU32 )
  REFL_CLASS_METHOD_ENTRY1(      EsBaseIntfPtr,              cr_EsBinBuffer )
  REFL_CLASS_METHOD_ENTRY2(      EsString,                    cr_EsBinBuffer,      ulong )
  REFL_CLASS_METHOD_ENTRY2(      EsBinBuffer,                cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY1(      bool,                        long )
  REFL_CLASS_METHOD_ENTRY2(      ulong,                      long,                ulong )
  REFL_CLASS_METHOD_ENTRY1(      ulong,                      long )
  REFL_CLASS_METHOD_ENTRY3(      ulong,                      long,                ulong,        ulong )
  REFL_CLASS_METHOD_ENTRY1(      EsVariant,                  cr_EsString )
  REFL_CLASS_METHOD_ENTRY3(      EsBaseIntfPtr,              cr_EsString,        ulong,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR2(                              cr_EsVariant,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY0(      EsString )
  REFL_CLASS_METHOD_ENTRY2(      bool,                       cr_EsString,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY_NR2(                               cr_EsString,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY3(      EsBaseIntfPtr,              cr_EsString,        cr_EsString,   cr_EsString )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              cr_EsString,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY4(      EsBaseIntfPtr,              cr_EsString,        cr_EsString,   cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR4(                              double,              double,        double,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY_NR4(                              long,                long,          long,          cr_EsString )
  REFL_CLASS_METHOD_ENTRY_NR4(                              ulong,              ulong,        ulong,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY_NR4(                              llong,              llong,        llong,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY_NR4(                              ullong,              ullong,        ullong,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY3(      EsString,                    cr_EsString,        cr_EsString,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY2(      EsBaseIntfPtr,              cr_EsBaseIntfPtr,    cr_EsString )
  REFL_CLASS_METHOD_ENTRY0(      bool  )
  REFL_CLASS_METHOD_ENTRY2(      EsBinBuffer,                cr_EsBinBuffer,     cr_EsString )
  REFL_CLASS_METHOD_ENTRY2(      EsString,                   cr_EsString,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY1(      esU16,                      esU16 )
  REFL_CLASS_METHOD_ENTRY1(      esU32,                      esU32 )
  REFL_CLASS_METHOD_ENTRY1(      esU64,                      esU64 )
  REFL_CLASS_METHOD_ENTRY1(      double,                     double )
  REFL_CLASS_METHOD_ENTRY2(      bool,                       double,             double )
  REFL_CLASS_METHOD_ENTRY3(      bool,                       double,             double,       ulong )
  REFL_CLASS_METHOD_ENTRY_NR7(                              cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant, cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY7(      EsVariant,                  cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY0(     double )
  REFL_CLASS_METHOD_ENTRY1(     double,                     long )
  REFL_CLASS_METHOD_ENTRY2(     double,                     double,             ulong )
  REFL_CLASS_METHOD_ENTRY2(     EsBaseIntfPtr,              cr_EsVariant,       ulong )
  REFL_CLASS_METHOD_ENTRY3(     EsBaseIntfPtr,              cr_EsString,        cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY3(      EsVariant,                  cr_EsVariant,        cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY5(      EsVariant,                  cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY6(      EsVariant,                  cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY7(      EsVariant,                  cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR3(                              cr_EsVariant,        cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR4(                              cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR5(                              cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR6(                              cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY_NR7(                              cr_EsVariant,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY2(     EsString,                   long,               ulong )
  REFL_CLASS_METHOD_ENTRY2(     long,                       cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY2(     EsString,                   ulong,              ulong )
  REFL_CLASS_METHOD_ENTRY2(     ulong,                      cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY2(     EsString,                   ullong,             ulong )
  REFL_CLASS_METHOD_ENTRY2(     ullong,                     cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY2(     EsString,                   llong,              ulong )
  REFL_CLASS_METHOD_ENTRY2(     llong,                      cr_EsString,        ulong )
  REFL_CLASS_METHOD_ENTRY1(     EsString,                   double )
  REFL_CLASS_METHOD_ENTRY1(     double,                     cr_EsString )
  REFL_CLASS_METHOD_ENTRY1(     EsVariant,                  double )
  REFL_CLASS_METHOD_ENTRY2(     double,                     double,             double )
  REFL_CLASS_METHOD_ENTRY3(     double,                     double,             double,       double )
  REFL_CLASS_METHOD_ENTRY4(     double,                     double,             double,       double,       double )
  REFL_CLASS_METHOD_ENTRY7(      EsString,                    cr_EsString,        cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(     bool,                       double )
  REFL_CLASS_METHOD_ENTRY0(     cr_EsString )
  REFL_CLASS_METHOD_ENTRY0(     ulong )
  REFL_CLASS_METHOD_ENTRY1(     long,                       ulong )
  REFL_CLASS_METHOD_ENTRY2(     long,                       ulong,              ulong )
  REFL_CLASS_METHOD_ENTRY3(     long,                       ulong,              ulong,        ulong )
  REFL_CLASS_METHOD_ENTRY4(     long,                       ulong,              ulong,        ulong,        ulong )
  REFL_CLASS_METHOD_ENTRY3(     EsBaseIntfPtr,              ulong,              ulong,        cr_EsString )
  REFL_CLASS_METHOD_ENTRY2(     EsBaseIntfPtr,              ulong,              cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY3(     EsBaseIntfPtr,              ulong,              ulong,        cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY1(     EsString,                   long )
  REFL_CLASS_METHOD_ENTRY_NR1(                              long )
  REFL_CLASS_METHOD_ENTRY4(      EsString,                    cr_EsString,        cr_EsString,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY5(      EsString,                    cr_EsString,        cr_EsString,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY6(      EsString,                    cr_EsString,        cr_EsString,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY7(      EsString,                    cr_EsString,        cr_EsString,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant,  cr_EsVariant )
  REFL_CLASS_METHOD_ENTRY4(     EsBaseIntfPtr,              cr_EsBinBuffer,     esU8,         ulong,        ulong)
  REFL_CLASS_METHOD_ENTRY4(     EsBaseIntfPtr,              cr_EsBinBuffer,     esU16,        ulong,        ulong)
  REFL_CLASS_METHOD_ENTRY4(     EsBaseIntfPtr,              cr_EsBinBuffer,     esU32,        ulong,        ulong)
REFL_CLASS_METHOD_ENTRIES_END

// undefine all. do not change these lines
#undef REFL_METHOD_ENTRIES_BEGIN
#undef REFL_METHOD_ENTRY0
#undef REFL_METHOD_ENTRY1
#undef REFL_METHOD_ENTRY2
#undef REFL_METHOD_ENTRY3
#undef REFL_METHOD_ENTRY4
#undef REFL_METHOD_ENTRY5
#undef REFL_METHOD_ENTRY6
#undef REFL_METHOD_ENTRY7
#undef REFL_METHOD_ENTRY_NR0
#undef REFL_METHOD_ENTRY_NR1
#undef REFL_METHOD_ENTRY_NR2
#undef REFL_METHOD_ENTRY_NR3
#undef REFL_METHOD_ENTRY_NR4
#undef REFL_METHOD_ENTRY_NR5
#undef REFL_METHOD_ENTRY_NR6
#undef REFL_METHOD_ENTRY_NR7
#undef REFL_CONST_METHOD_ENTRY0
#undef REFL_CONST_METHOD_ENTRY1
#undef REFL_CONST_METHOD_ENTRY2
#undef REFL_CONST_METHOD_ENTRY3
#undef REFL_CONST_METHOD_ENTRY4
#undef REFL_CONST_METHOD_ENTRY5
#undef REFL_CONST_METHOD_ENTRY6
#undef REFL_CONST_METHOD_ENTRY7
#undef REFL_CONST_METHOD_ENTRY_NR0
#undef REFL_CONST_METHOD_ENTRY_NR1
#undef REFL_CONST_METHOD_ENTRY_NR2
#undef REFL_CONST_METHOD_ENTRY_NR3
#undef REFL_CONST_METHOD_ENTRY_NR4
#undef REFL_CONST_METHOD_ENTRY_NR5
#undef REFL_CONST_METHOD_ENTRY_NR6
#undef REFL_CONST_METHOD_ENTRY_NR7
#undef REFL_METHOD_ENTRIES_END
#undef REFL_CLASS_METHOD_ENTRIES_BEGIN
#undef REFL_CLASS_METHOD_ENTRY0
#undef REFL_CLASS_METHOD_ENTRY1
#undef REFL_CLASS_METHOD_ENTRY2
#undef REFL_CLASS_METHOD_ENTRY3
#undef REFL_CLASS_METHOD_ENTRY4
#undef REFL_CLASS_METHOD_ENTRY5
#undef REFL_CLASS_METHOD_ENTRY6
#undef REFL_CLASS_METHOD_ENTRY7
#undef REFL_CLASS_METHOD_ENTRY_NR0
#undef REFL_CLASS_METHOD_ENTRY_NR1
#undef REFL_CLASS_METHOD_ENTRY_NR2
#undef REFL_CLASS_METHOD_ENTRY_NR3
#undef REFL_CLASS_METHOD_ENTRY_NR4
#undef REFL_CLASS_METHOD_ENTRY_NR5
#undef REFL_CLASS_METHOD_ENTRY_NR6
#undef REFL_CLASS_METHOD_ENTRY_NR7
#undef REFL_CLASS_METHOD_ENTRIES_END