#ifndef _build_h_
#define _build_h_

// esmath component version file
// DO NOT CHANGE!, this file is automatically generated by CMake 
// during build configueration stage

#include <../version.h>

// increment this value when publishing new changes in release
#define COMPONENT_BUILD_NUM						    1
#define COMPONENT_DESCRIPTION_STRING	    esT("ESFWX Math Library")
#define COMPONENT_INTERNAL_NAME				    esT("esmath")
#define COMPONENT_ORIGINAL_NAME				    esT("esmath")
#define COMPONENT_VERSION_STRING          esT("1.24.1")

#ifdef _DEBUG
#	define COMPONENT_VERSION_STRING_LONG		COMPONENT_DESCRIPTION_STRING esT(" ") COMPONENT_VERSION_STRING esT(" DEBUG")
#else
#	define COMPONENT_VERSION_STRING_LONG  	COMPONENT_DESCRIPTION_STRING esT(" ") COMPONENT_VERSION_STRING 
#endif

#endif 
