// macro-x definitions file for ftdi channel implementation
//

// ftdi driver entries. each entry contains call name w\o FT_ prefix (which is added automatically)
// and the list of parameter types passed to the driver entry call
//
FTDI_DRIVER_ENTRY2( Open, int, FT_HANDLE* )
FTDI_DRIVER_ENTRY3( OpenEx, PVOID, DWORD, FT_HANDLE* )
FTDI_DRIVER_ENTRY1( CreateDeviceInfoList, LPDWORD )
FTDI_DRIVER_ENTRY3( ListDevices, PVOID, PVOID, DWORD )
FTDI_DRIVER_ENTRY2( GetDeviceInfoList, FT_DEVICE_LIST_INFO_NODE*, LPDWORD)
FTDI_DRIVER_ENTRY1( Close, FT_HANDLE )
FTDI_DRIVER_ENTRY4( Read, FT_HANDLE, LPVOID, DWORD, LPDWORD )
FTDI_DRIVER_ENTRY4( Write, FT_HANDLE, LPVOID, DWORD, LPDWORD )
FTDI_DRIVER_ENTRY8( IoCtl, FT_HANDLE, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPOVERLAPPED )
FTDI_DRIVER_ENTRY2( SetBaudRate, FT_HANDLE, ULONG )
FTDI_DRIVER_ENTRY2( SetDivisor, FT_HANDLE, USHORT )
FTDI_DRIVER_ENTRY4( SetDataCharacteristics, FT_HANDLE, UCHAR, UCHAR, UCHAR )
FTDI_DRIVER_ENTRY4( SetFlowControl, FT_HANDLE, USHORT, UCHAR, UCHAR )
FTDI_DRIVER_ENTRY1( ResetDevice, FT_HANDLE )
FTDI_DRIVER_ENTRY1( SetDtr, FT_HANDLE )
FTDI_DRIVER_ENTRY1( ClrDtr, FT_HANDLE )
FTDI_DRIVER_ENTRY1( SetRts, FT_HANDLE )
FTDI_DRIVER_ENTRY1( ClrRts, FT_HANDLE )
FTDI_DRIVER_ENTRY2( GetModemStatus, FT_HANDLE, ULONG* )
FTDI_DRIVER_ENTRY5( SetChars, FT_HANDLE, UCHAR,	UCHAR, UCHAR, UCHAR )
FTDI_DRIVER_ENTRY2( Purge, FT_HANDLE, ULONG )
FTDI_DRIVER_ENTRY3( SetTimeouts, FT_HANDLE, ULONG, ULONG )
FTDI_DRIVER_ENTRY2( GetQueueStatus, FT_HANDLE, DWORD* )
FTDI_DRIVER_ENTRY3( SetEventNotification, FT_HANDLE, DWORD,	PVOID )
FTDI_DRIVER_ENTRY2( GetEventStatus, FT_HANDLE, DWORD* )
FTDI_DRIVER_ENTRY4( GetStatus, FT_HANDLE, DWORD*, DWORD*, DWORD* )
FTDI_DRIVER_ENTRY1( SetBreakOn, FT_HANDLE )
FTDI_DRIVER_ENTRY1( SetBreakOff, FT_HANDLE )
FTDI_DRIVER_ENTRY2( SetWaitMask, FT_HANDLE, DWORD )
FTDI_DRIVER_ENTRY2( WaitOnMask, FT_HANDLE, DWORD* )
FTDI_DRIVER_ENTRY1( StopInTask, FT_HANDLE ) 
FTDI_DRIVER_ENTRY1( RestartInTask, FT_HANDLE ) 
FTDI_DRIVER_ENTRY2( SetLatencyTimer, FT_HANDLE, UCHAR )
FTDI_DRIVER_ENTRY2( GetLatencyTimer, FT_HANDLE, PUCHAR )
FTDI_DRIVER_ENTRY3( SetBitMode, FT_HANDLE, UCHAR, UCHAR )
FTDI_DRIVER_ENTRY2( GetBitMode, FT_HANDLE, PUCHAR ) 
FTDI_DRIVER_ENTRY3( SetUSBParameters, FT_HANDLE, DWORD, DWORD )

// macro definitions housekeeping
#undef FTDI_DRIVER_ENTRY0
#undef FTDI_DRIVER_ENTRY1
#undef FTDI_DRIVER_ENTRY2
#undef FTDI_DRIVER_ENTRY3
#undef FTDI_DRIVER_ENTRY4
#undef FTDI_DRIVER_ENTRY5
#undef FTDI_DRIVER_ENTRY6
#undef FTDI_DRIVER_ENTRY7
#undef FTDI_DRIVER_ENTRY8
